service: import-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::node-aws-file-storage"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::node-aws-file-storage/*"

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http: GET import
        request:
          parameters:
            querystrings:
              name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: node-aws-file-storage
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
